//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mediathequeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exemplaire()
        {
            this.Notification = new HashSet<Notification>();
        }
    
        public int IdExemplaire { get; set; }
        public System.DateTime DateEmprunt { get; set; }
        public int IdUsager { get; set; }
        public int IdDocument { get; set; }
        public int IdStatutExemplaire { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual StatutExemplaire StatutExemplaire { get; set; }
        public virtual Usager Usager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
