//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mediathequeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int IdNotification { get; set; }
        public string LibelleNotification { get; set; }
        public int TypeNotification { get; set; }
        public System.DateTime DateNotification { get; set; }
        public Nullable<int> IdUsager { get; set; }
        public Nullable<int> IdFournisseur { get; set; }
        public int IdExemplaire { get; set; }
    
        public virtual Exemplaire Exemplaire { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Usager Usager { get; set; }
    }
}
