//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mediathequeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usager()
        {
            this.Exemplaire = new HashSet<Exemplaire>();
            this.Notification = new HashSet<Notification>();
            this.Paiement = new HashSet<Paiement>();
        }
    
        public int IdUsager { get; set; }
        public string NomUsager { get; set; }
        public string PrenomUsager { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public System.DateTime DateInscription { get; set; }
        public byte Caution { get; set; }
        public int IdCoordonnees { get; set; }
        public int IdStatutUsager { get; set; }
        public int IdTypeAbonnement { get; set; }
    
        public virtual Coordonnees Coordonnees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exemplaire> Exemplaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiement { get; set; }
        public virtual StatutUsager StatutUsager { get; set; }
        public virtual TypeAbonnement TypeAbonnement { get; set; }
    }
}
